### ISSUE TITLE
Connect as400

### ISSUE THREAD

**Issue by akilinomendez** [Hyurl/modelar-ibmdb-adapter#1]
Hello, I need to connect to as400 with db 9.7, but when executing a select one, I receive this error:
{ Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "*******".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001

Changing from port to 446 I received this:
{ Error: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968

  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968\n',
  state: '42968' }

I do not have a license for db2cli, but the odbc connection is active because I can use isql to select.

Can this package use the unixodbc driver?

Now I'm using the node-odbc package from wankdanker, but I have a lot of problems with the connections and the characters, but the database is in the westers eu code

**Comment by Hyurl** [comment]
I didn't realize this before, but I‘ve got a brief check-out of node-ibm_db module, though it doesn't mention too much about ODBC in its API specification, I've found some details in its source code, the solution should be done today, and I will notify you as soon as possible, thanks for the issue.

**Comment by Hyurl** [comment]
When you're using wankdanker's node-odbc module, is it using a connection string to connect the database host? with or without protocol? My adapter uses ibm_db module, it doesn't say much about the unixdriver you suggest. I'm not very familiar with odbc, now I'm checking details on IBM, but I want you to give me some information that you know and see what I can do.

**Comment by Hyurl** [comment]
When I test this adapter today, I faced the same problem as you were, but it soon disappeared. I don't know where the problem is, I am using the DB2 EX on windows. Now I just modified the source code of this package (and modelar as well), to allow it supporting customized connection string. you can download the new version to test it in your environment, hope it'd help.

**Comment by akilinomendez** [comment]
Thanks for your prompt response.

One of the big problems is the db2 in its old version that does not support too many things. Ahor shows the following error:

[IBM] [CLI Driver] SQL30082N Security processing failed with reason "17"

Another option would be to use node-jt400 (java), I've tried several queries and it seems to work without any configuration. Would it be possible to implement it in "modelar"?

**Comment by Hyurl** [comment]
I'm not familiar with jt400, and node-jt400 doesn't provide enough details about the package, it may be able to connect and run queries, but many other features such as max connection size, timeout checking are not guaranteed. I can only implement those functions I've known, if you can provide details about jt400, it would be the best.

**Comment by Hyurl** [comment]
I've written a jt400 adapter and commit it to [https://github.com/Hyurl/modelar-jt400-adapter](https://github.com/Hyurl/modelar-jt400-adapter), but since I use db2_11, I'm unable to test it, it would be very helpful if you could clone the repository (do not use npm to install) to your disk and do some test.

**Comment by akilinomendez** [comment]
It's wonderful, it works with the tests I did, I'll keep trying and if I find a problem I'll tell you.
To operate remove port and database in "DB.setAdapter" 

Thank you.

**Comment by Hyurl** [comment]
Are you saying that connect via jt400 doesn't require the `port` and `database`?
And please test the example that in `modelar/test`, which covers the major features of modelar.
